steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/brennon-loveless/javascript30-nginx:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/brennon-loveless/javascript30-nginx:latest', 'gcr.io/brennon-loveless/javascript30-nginx:$SHORT_SHA' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/brennon-loveless/javascript30-nginx:latest' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/brennon-loveless/javascript30-nginx:$SHORT_SHA' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['-n', 'javascript30', 'set', 'image', 'deployment/javascript30', 'nginx=gcr.io/brennon-loveless/javascript30-nginx:$SHORT_SHA' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['-n', 'javascript30', 'rollout', 'status', '-f', 'k8s/010-nginx-deployment.yaml' ]

options:
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1-a'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demon-k8s'

