version: '3.2'
services:
  nginx:
    build: .
    image: 391324319136.dkr.ecr.us-west-2.amazonaws.com/javascript30-nginx
    ports:
      - "80:80"
    volumes:
      - "./web:/usr/share/nginx/html"
