apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: javascript30
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - javascript30.brennonloveless.com
      secretName: javascript30-crt
  rules:
    - host: javascript30.brennonloveless.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-cluster-ip-service
              servicePort: 80

